# Site settings
title: 技術メモ
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "http://133.242.129.199/blog" # the subpath of your site, e.g. /blog/
url: "http://133.242.129.199/" # the base hostname & protocol for your site
twitter_username: mitake_ck
github_username:  mitakeck

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink",
                 "tables", "with_toc_data"]
